from rest_framework import serializers


class InitiatePaymentSerializer(serializers.Serializer):
    """Frontend sends this before opening the Interswitch modal."""

    tx_ref   = serializers.CharField(max_length=256, help_text="Unique transaction reference generated by frontend.")
    amount   = serializers.FloatField(help_text="Amount in NGN (e.g. 1000.00 for filing fee).")
    tax_year = serializers.IntegerField(help_text="The tax year this payment covers.")


class WebhookPayloadSerializer(serializers.Serializer):
    """Interswitch webhook payload."""

    txnref = serializers.CharField(help_text="Transaction reference.")
    amount = serializers.CharField(help_text="Amount paid (as string from Interswitch).")
    resp   = serializers.CharField(help_text="Response code. '00' means success.")
    hash   = serializers.CharField(help_text="SHA-512 signature for verification.")


class PaymentSuccessResponseSerializer(serializers.Serializer):
    status   = serializers.ChoiceField(choices=["success"])
    rrr_code = serializers.CharField(help_text="Government payment reference e.g. NRS-4829-1102.")
    message  = serializers.CharField()


class PaymentErrorResponseSerializer(serializers.Serializer):
    status  = serializers.ChoiceField(choices=["error"])
    message = serializers.CharField()


class InitiatePaymentResponseSerializer(serializers.Serializer):
    status  = serializers.ChoiceField(choices=["success"])
    message = serializers.CharField()
    tx_ref  = serializers.CharField()